### ISSUE TITLE
BUG : Cannot open Users near me

### ISSUE THREAD

**Issue by sakdec10** [justynth/Friend_Builder#110]
When I login and click on users near me button the app crashes.

I'm using Android 8.0 Oreo

**Comment by btackett3** [comment]
I could recreate the crash in Oreo.  When the user's location is not found, it creates a Null Pointer Exception.  This does not happen with Android API 27.

![image](https://user-images.githubusercontent.com/20663749/38156768-ae5256d2-344e-11e8-87fd-b07e6660a016.png)

Solution A:  Set a default behavior for when the user's location is not found.  Instead of creating location objects for the other users, the distance field should be set to the string "undefined".

Solution B:  Set an async while-loop that just shows some message while waiting to find their location.

Solution C:  Do A, but keep trying to find their location without them needing to refresh the page.

Assigned to Brian.
